id: I17855885
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:42:04+00:00'
last_modified: '2022-06-07T18:04:55.771863+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17233
  title: ཚེ་ཆོག་བདུད་རྩིའི་བུམ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    98B8:
      image_group_id: I8LS17250
      title: ''
      total_pages: 46
      order: 1
      base_file: 98B8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
