id: P003173
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17233
  title: ཚེ་ཆོག་བདུད་རྩིའི་བུམ་བཟང་།
  author: ''
  volumes:
    dd8cd37a253b4774ae27758b843670aa:
      image_group_id: I8LS17250
      title: ''
      volume_number: 1
      total_pages: 46
      base_file: v001.txt
